# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Soicitando ao usuário que insira o número

 Escreva("digite um numero=15")
 Leia("Digite um número:15")

 #Verificando se o número é positivo, negativo ou zero
  Se numero > 0

  Escreva("O número é positivo")
  leia("o numero é positivo")
  else:
  numero < 0

  Senão("O número é negativo")

 Escreva("O número é quinze")
 leia("O número é quinze")